name: Checks

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  infrastructure:
    permissions:
      contents: write
    uses: martoc/workflow-infrastructure/.github/workflows/infrastructure.yml@v0
